# lightning.pytorch==2.0.1.post0
seed_everything: 42
trainer:
  default_root_dir: runs/
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: null
      save_dir: runs/
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: cultural-heritage
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      job_type: null
      config: null
      entity: null
      reinit: null
      tags: null
      group: null
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: null
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      settings: null
  callbacks:
    class_path: callbacks.predictions.LogPredictionSamplesCallback
  fast_dev_run: false
  max_epochs: 1
  min_epochs: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  accumulate_grad_batches: 16
  log_every_n_steps: 10
model:
  model_name_or_path: microsoft/git-base
  learning_rate: 5.0e-05
  warmup_steps: 500
  weight_decay: 0.0
  metrics:
    - class_path: model.CocoScore
    - class_path: torchmetrics.text.BERTScore
      init_args:
        model_name_or_path: distilbert-base-uncased
        batch_size: 16
        lang: en
        max_length: 512
  generation:
    num_beams: 1
    do_sample: true
    num_return_sequences: 1
    #top_k: 50
    max_length: 512
    temperature: 0.7
data:
  img_dir: data/artpedia/
  ann_file: data/artpedia/artpedia_augmented.json
  batch_size: 2
  model_name_or_path: microsoft/git-base
  captions_per_image: 10
  num_workers: 6
ckpt_path: null
